"use client";
import type { Metadata } from "next";

import { ethers } from "ethers";
import Image from "next/image";
import Link from "next/link";
import React, { createContext, useContext, useEffect, useState } from "react";

import NFTMusicPlayerAbi from "../abi/NFTMusicPlayer.json";
import NFTMusicPlayerAddress from "../abi/NFTMusicPlayer-address.json";
import logo from "../public/logo.png";
import "./globals.css";

declare global {
  interface Window {
    ethereum: any;
  }
}

interface ContextProps {
  account: null | string;
  contract: ethers.Contract;
  loading: boolean;
  web3Handler: () => Promise<void>;
}

const BlockchainContext = createContext<Partial<ContextProps>>({});

export const useBlockchain = () => useContext(BlockchainContext);

const dummyContract = new ethers.Contract(
  "0x0000000000000000000000000000000000000000", // Dummy address
  new ethers.utils.Interface([]), // Empty ABI
  ethers.getDefaultProvider() // Default provider
);

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [loading, setLoading] = useState(true);
  const [account, setAccount] = useState<null | string>(null);
  const [contract, setContract] = useState(dummyContract);

  const web3Handler = async () => {
    const accounts = await window.ethereum.request({ method: "eth_requestAccounts" });
    setAccount(accounts[0]);
    const provider = new ethers.providers.Web3Provider(window.ethereum);
    const signer = provider.getSigner();
    loadContract(signer);
  };

  const loadContract = async (signer: ethers.providers.JsonRpcSigner) => {
    const contract = new ethers.Contract(NFTMusicPlayerAddress.address, NFTMusicPlayerAbi.abi, signer);
    setContract(contract);
    setLoading(false);
  };

  useEffect(() => {
    if (typeof window.ethereum !== "undefined") {
      web3Handler();
    }
  }, []);

  return (
    <html lang="en">
      <body>
        <div className="text-center">
          <nav className="bg-secondary text-white p-4">
            <div className="container mx-auto flex justify-between items-center">
              <Link className="flex items-center" href="/">
                <Image alt="Logo" height={40} src={logo} width={40} />
                <span className="ml-2">Music NFT player</span>
              </Link>
              <div className="flex items-center">
                <Link href="/">Home</Link>
                <Link href="/tokens">My Tokens</Link>
                <Link href="/resales">My Resales</Link>
                {account ? (
                  <a
                    className="mx-4"
                    href={`https://etherscan.io/address/${account}`}
                    rel="noopener noreferrer"
                    target="_blank"
                  >
                    {account.slice(0, 5) + "..." + account.slice(38, 42)}
                  </a>
                ) : (
                  <button className="bg-white text-black px-4 py-2 rounded" onClick={web3Handler}>
                    Connect Wallet
                  </button>
                )}
              </div>
            </div>
          </nav>
          <div>
            <BlockchainContext.Provider value={{ account, contract, loading, web3Handler }}>
              {loading ? (
                <div className="flex justify-center items-center h-screen">
                  <div className="loader ease-linear rounded-full border-4 border-t-4 border-gray-200 h-12 w-12 mb-4"></div>
                  <p className="mx-3 my-0">Awaiting Metamask Connection...</p>
                </div>
              ) : (
                children
              )}
            </BlockchainContext.Provider>
          </div>
        </div>
      </body>
    </html>
  );
}
