/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8xm952KA7nt
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { TooltipContent } from "@radix-ui/react-tooltip";
import Image from "next/image";
import React, { Dispatch, SetStateAction, useEffect, useRef } from "react";
import { MdOutlineRepeat, MdOutlineRepeatOne, MdOutlineShuffle } from "react-icons/md";

import { IItem, repeatModes } from "../app/page";
import { Tooltip, TooltipProvider, TooltipTrigger } from "../src/components/ui/tooltip";

import Logo from "/public/logo.png";

interface PlaylistBarProps {
  currentAudioIndex: number;
  handleRepeatModeChange: () => void;
  handleShuffle: () => void;
  isShuffle: boolean;
  repeatMode: repeatModes;
  setCurrentAudioIndex: Dispatch<SetStateAction<number>>;
  tracks: IItem[];
}

export const PlaylistBar: React.FC<PlaylistBarProps> = ({
  currentAudioIndex,
  handleRepeatModeChange,
  handleShuffle,
  isShuffle,
  repeatMode,
  setCurrentAudioIndex,
  tracks
}) => {
  const trackRefs = useRef<(HTMLDivElement | null)[]>([]);

  // auto scroll to currently playing song
  useEffect(() => {
    if (currentAudioIndex !== null && trackRefs.current[currentAudioIndex] !== null) {
      trackRefs.current[currentAudioIndex]?.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [currentAudioIndex]);

  // format duration of each song to mm:ss from seconds
  const formatTime = (seconds: number) => {
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.floor(seconds % 60);
    return `${minutes}:${remainingSeconds < 10 ? "0" : ""}${remainingSeconds}`;
  };

  return (
    <div className="bg-background rounded-lg border px-6 py-4 w-full max-w-md h-full">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold">Playlist</h2>
        <div className="flex items-center gap-2">
          <Button onClick={handleShuffle} size="sm" variant="ghost">
            <MdOutlineShuffle className={cn("w-6 h-6 text-primary/50", { "text-primary": isShuffle })} />
          </Button>
          <Button onClick={handleRepeatModeChange} size="sm" variant="ghost">
            {repeatMode === repeatModes.NONE ? (
              <MdOutlineRepeat className="w-6 h-6 text-primary/50" />
            ) : repeatMode === repeatModes.PLAYLIST ? (
              <MdOutlineRepeat className="w-6 h-6 text-primary" />
            ) : (
              <MdOutlineRepeatOne className="w-6 h-6 text-primary" />
            )}
          </Button>
        </div>
      </div>
      <ScrollArea className="h-[500px]">
        <div className="grid gap-4 pr-4">
          {tracks.map((item, idx) => (
            <div
              className={"flex items-center gap-4 cursor-pointer"}
              key={idx}
              onClick={() => setCurrentAudioIndex(idx)}
              ref={el => {
                trackRefs.current[idx] = el as HTMLDivElement | null;
              }}
            >
              <Image alt={item.name} height={36} src={item.identicon ?? Logo} width={36} />
              <div className="flex-1 text-left">
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger>
                      <div className="track-name text-base text-left line-clamp-1">{item.name}</div>
                    </TooltipTrigger>
                    <TooltipContent className="border px-2 bg-background rounded-lg text-sm" side="bottom">
                      {item.name}
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
                <div className="text-sm text-muted-foreground line-clamp-1">{item.artist}</div>
              </div>
              <div className="text-sm text-muted-foreground">{formatTime(item.duration)}</div>{" "}
              {idx === currentAudioIndex && (
                <div className="bg-primary text-primary-foreground rounded-full px-2 py-1 text-xs">Playing</div>
              )}
            </div>
          ))}
        </div>
      </ScrollArea>
    </div>
  );
};
